#!/bin/bash

while getopts ":c:p:d:s:" q; do
    case "${q}" in
        c) c=${OPTARG} ;;
        p) p=${OPTARG} ;;
        d) d=${OPTARG} ;;
        s) s=${OPTARG} ;;
        *) usage ;;
    esac
done

# echo "c = ${c}" #c - database contaianer name
# echo "p = ${p}" #p - password
# echo "d = ${d}" #d - database name
# echo "s = ${s}" #s - service name



echo 'db._createDatabase("myDatabase");' | arangosh --server.endpoint tcp://${c}:8529 --server.password ${p}

#echo 'db._createDatabase("myDatabase");' | arangosh
#arangosh --server.endpoint tcp://${c}:8529 --server.password ${p} 
#db._createDatabase(${d})


#foxx-manager --server.endpoint tcp://${c}:8529 --server.database ${d} --server.password ${p} install /arango/arangodbconfig.zip /${s}

# create service 