#!/bin/bash

while getopts ":u:a:s:" q; do
    case "${q}" in
        u) u=${OPTARG} ;;
        a) a=${OPTARG} ;;
        s) s=${OPTARG} ;;
        *) usage ;;
    esac
done

# echo "u = ${u}" #u - rancher url
# echo "a = ${a}" #a - rancher access
# echo "s = ${s}" #s - rancher secret

# Update Rancher vars if set
if [[ -n "${u}" && -n "${a}" && -n "${s}" ]]
then
    export RANCHER_URL=${u}
    export RANCHER_ACCESS_KEY=${a}
    export RANCHER_SECRET_KEY=${s}
fi

# Add commands to run backups 
# EXAMPLE rancher/docker exec arangodbutil /scripts/arangobackup -d databasename -e tcp://endpoint:8529 -o true
rancher exec arangodbutil /scripts/arangobackup -d databasename -e tcp://endpoint:8529 -o true
rancher exec arangodbutil /scripts/arangobackup -d databasename -c containerName -o true